test_username = "xpath://input[@id = 'UserName']"
test_password = "xpath://input[@id = 'PassWord']"
test_login = "id:submit"
test_login_verify = "Welcome to GN Online Services"
contact_button = "xpath:/html/body/div[1]/div[1]/div/a[2]"
contact_verify = "Contact GN Online Services"
home_button = "xpath:/html/body/div[1]/div[1]/div/a[1]"
register_button = "xpath://a[text() = 'Register']"
register_verify = "GN Online Services - Registration"
account_no ="id:AccountNumber"
register_username = "id:UserName"
register_email = "id:EmailAddress"
register_fname ="id:FirstName"
register_phone = "id:Phone"
register_list_country = "Country"
register_list_languages = "PreferredLanguage"
register_conf_email = "id:ConfirmEmail"
register_lname = "id:LastName"
register_checkbox = "id:mycheckbox"
register_submit = "id:submitbutton"
register_verify_invalid = "There is an issue with your account number and/or email address"
login_button = "id:lnkLogin"
login_email = "xpath://input[@id ='UserNameOrEmail']"
login_next = "id:btnNext"
login_cookie = "id:CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll"
login_password = "id:password"
login_continue = "id:next"
login_verify = "We can't seem to find your account"